# site settings
title: Sat Sampling
subtitle: Survey Sampling using Aerial Imagery
email: bquast@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/massively" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Bastiaan Quast
street_address: 1234 Somewhere Road
city: Geneva
state: TN
zip_code: 1201
country: Switzerland
phone: +41 786988330

# social settings
500px_url:
facebook_url:
github_url: https://github.com/
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
