# site settings
title: SatSampling
subtitle: Survey Sampling using Aerial Imagery
email: bquast@gmail.com
description: SatSampling provides sampling methods for surveys based on aerial imagery and AI-based methods for household localisation.
baseurl: "/massively" # the subpath of your site, e.g. /blog
url: "https://satsampling.github.io" # the base hostname & protocol for your site
author: Bastiaan Quast
street_address: Quai de Mont Blanc 1
city: Geneva
state: Switzerland
zip_code: 1201
country:
phone: +41 78.69.88.330

# social settings
500px_url:
facebook_url: https://www.facebook.com/SatSampling-1917121405242312/
github_url: https://github.com/satsampling
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
